<?php
/**
 * Created by PhpStorm.
 * User: wade
 * Date: 2018/7/22
 * Time: 下午2:50
 */

use Goutte\Client;
use Sunra\PhpSimple\HtmlDomParser;


class testCrawler extends PHPUnit\Framework\TestCase
{
    protected $url;
    protected $html;

    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->url = 'https://www.kingstone.com.tw/basics/basics.asp?kmcode=2013120471221&actid=ActBillBoard';

        $client  = new Client();
        $crawler = $client->request('GET', $this->url);

        $this->html = $crawler->html();
    }

    /**
     * 擷取「ISBN 國際標準書號」
     */
    public function testGetISBN(): void
    {
        // Arrange

        // Act
        $match = [];
        preg_match('/<span>ISBN：<\/span><em>(\d+)<\/em>/', $this->html, $match);

        // Assert
        $this->assertEquals($match[1], '9789864591374');
    }

    /**
     * 擷取「書名」
     */
    public function testGetBookName(): void
    {
        // Arrange

        // Act
        $match = [];
        preg_match('/<h1>(.*)\r\n/', $this->html, $match);

        // Assert
        $this->assertEquals('不需要電腦的程式設計課：從遊戲中學習電腦語言、鍛鍊運算思維，培育AI時代必備的數位素養', $match[1]);
    }

    /**
     * 擷取「作者」
     */
    public function testGetAuthor(): void
    {
        // Arrange

        // Act
        $match = [];
        preg_match('/<span>作者：<em><a.*;">(.*)<\/a>/', $this->html, $match);

        // Assert
        $this->assertEquals('養姆．克利斯欽', $match[1]);
    }

    /**
     * 擷取「出版社」
     */
    public function testGetPublishing(): void
    {
        // Arrange

        // Act
        $match = [];
        preg_match('/<span>出版社：<em><a.*;">(.*)<\/a>/', $this->html, $match);

        // Assert
        $this->assertEquals('積木      ', $match[1]);
    }

    /**
     * 擷取「譯者」
     */
    public function testGetTranslator(): void
    {
        // Arrange

        // Act
        $match = [];
        preg_match('/<span>譯者：<\/span><em>(.*)<\/em>/', $this->html, $match);

        // Assert
        $this->assertEquals('魏嘉儀', $match[1]);
    }

    /**
     * 擷取「副標題」
     */
    public function testGetSubTitle(): void
    {
        // Arrange

        // Act
        $match = [];
        preg_match('/<em><a href="#this".*;">(.*)<\/a><\/em>/', $this->html, $match);

        // Assert
        $this->assertEquals('How to Think Like a Coder without Even Trying', $match[1]);
    }

    /**
     * 擷取「出版日期」
     */
    public function testGetPublishDate(): void
    {
        // Arrange

        // Act
        $match = [];
        preg_match('/<span>出版日：<\/span><em>(.*)<\/em>/', $this->html, $match);

        // Assert
        $this->assertEquals('2018/6/7', $match[1]);
    }
}